---
# Main task file for VM management role
- name: Install qemu-guest-agent for better VM management
  package:
    name: qemu-guest-agent
    state: present
  become: true
  when: ansible_virtualization_type == "kvm"

- name: Enable and start qemu-guest-agent service
  service:
    name: qemu-guest-agent
    state: started
    enabled: yes
  become: true
  when: ansible_virtualization_type == "kvm"

- name: Configure VM hostname
  hostname:
    name: "{{ vm_hostname }}"
  become: true
  when: vm_hostname is defined

- name: Update /etc/hosts with hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ vm_hostname }}'
  become: true
  when: vm_hostname is defined

- name: Install vm packages
  package:
    name: "{{ vm_packages }}"
    state: present
  become: true
  when: vm_packages is defined