---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update package cache (RHEL/CentOS/Rocky)
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Upgrade all packages
  package:
    name: "*"
    state: latest
  register: upgrade_result

- name: Check if reboot is required (Debian/Ubuntu)
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_os_family == "Debian"

- name: Check if reboot is required (RHEL/CentOS)
  command: needs-restarting -r
  register: reboot_required_rhel
  failed_when: false
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Reboot if required
  reboot:
    msg: "Rebooting due to system updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: >
    (ansible_os_family == "Debian" and reboot_required_file.stat.exists) or
    (ansible_os_family == "RedHat" and reboot_required_rhel.rc == 1)