- name: Install and configure Docker
  hosts: all
  become: true
  vars:
    docker_repo_info:
      Ubuntu:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
        package_name: "docker-ce"
      Debian:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        gpg_url: "https://download.docker.com/linux/debian/gpg"
        package_name: "docker-ce"
      CentOS:
        repo: "https://download.docker.com/linux/centos/docker-ce.repo"
        gpg_url: "https://download.docker.com/linux/centos/gpg"
        package_name: "docker-ce"
      Rocky:
        repo: "https://download.docker.com/linux/centos/docker-ce.repo"
        gpg_url: "https://download.docker.com/linux/centos/gpg"
        package_name: "docker-ce"

  tasks:
    - name: Install prerequisite packages (Debian/Ubuntu)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install prerequisite packages (RHEL/CentOS/Rocky)
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Docker GPG key (Debian/Ubuntu)
      ansible.builtin.apt_key:
        url: "{{ docker_repo_info[ansible_distribution].gpg_url }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (Debian/Ubuntu)
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo_info[ansible_distribution].repo }}"
        state: present
        filename: docker
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (RHEL/CentOS/Rocky)
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        file: docker-ce
        baseurl: "{{ docker_repo_info[ansible_distribution].repo }}"
        gpgcheck: yes
        gpgkey: "{{ docker_repo_info[ansible_distribution].gpg_url }}"
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install Docker packages
      package:
        name: "{{ docker_repo_info[ansible_distribution].package_name }}"
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group (optional)
      user:
        name: ansible
        groups: docker
        append: yes