---
# Main tasks file for telegraf role

- name: Include telegraf installation tasks
  include_tasks: install.yml
  when: telegraf_install | default(false)

- name: Include telegraf configuration tasks
  include_tasks: configure.yml
  when: telegraf_enabled

- name: Disable and stop Telegraf if not enabled
  ansible.builtin.service:
    name: telegraf
    state: stopped
    enabled: no
  when: not telegraf_enabled